### ISSUE TITLE
Τι λάθος υπάρχει;

### ISSUE THREAD

**Issue by linuxergr** [billniakas/live24parser#2]
Καλησπέρα,

Κατέβασα το τελευταίο release από https://github.com/billniakas/live24parser/releases/tag/v0.3

Δεν ξέρω αν έκανα κάτι λάθος, ή αν ευθύνεται το script.

![Screenshot](https://i.imgur.com/ZSb8WtH.png)

**Comment by billniakas** [comment]
Ούτε το help δε διάβασες :P 

Πρώτα περιοχή και μετά τύπος λίστας.
Θα σε δείρω.
